cp = -cp CITS2200.jar:.

StackBlock : StackBlock.java CITS2200.jar StackBlockTest.java
	javac $(cp) StackBlock.java StackBlockTest.java

StackLinked : StackLinked.java Link.java CITS2200.jar StackLinkedTest.java
	javac $(cp) StackLinked.java Link.java StackLinkedTest.java
